import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { access, chmod, mkdir, readFile, readdir, rmdir, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import type { HarnessAdapter, InstallReport, UninstallReport } from "../types.js";
import type { LeanRigorConfig, ModelTier } from "../../config/schema.js";
import { isClaudeAlias, resolveModelTier } from "../../config/models.js";
import { ensureGitignore, checkTrackedLeanrigorFiles } from "../../config/bootstrap.js";
import { configFileExists, loadUserConfig, loadRepoPolicy } from "../../config/load.js";
import { ConfigScope } from "../../config/config-scope.js";

/** Version stamp embedded in every generated asset. Increment when assets change in a breaking way. */
export const ASSET_VERSION = 4;

/** String embedded in every LeanRigor-generated file for ownership detection. */
const OWNERSHIP_TOKEN = "generated_by: leanrigor";
const PROTECT_GIT_DEST = path.join(".claude", "leanrigor", "protect-git.sh");

/** Directory containing the Claude plugin source assets, resolved at runtime. */
function pluginDir(): string {
  return fileURLToPath(new URL("./plugin/", import.meta.url));
}

/** Repository/package root containing shared methodology assets. */
function packageRoot(): string {
  return path.resolve(pluginDir(), "..", "..", "..", "..");
}

const METHODOLOGY_FILES = [
  "core.md",
  "planning.md",
  "design.md",
  "implementation.md",
  "debugging.md",
  "testing.md",
  "review.md",
  "evidence.md",
  "safeguards.md",
  path.join("modes", "fast.md"),
  path.join("modes", "standard.md"),
  path.join("modes", "rigorous.md")
];

/** Deterministic SHA-256 of a string. */
function sha256(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex");
}

/** Return true when the file content was generated by LeanRigor. */
function isLeanRigorOwned(content: string): boolean {
  return content.includes(OWNERSHIP_TOKEN);
}

/**
 * Read a packaged asset and optionally substitute template variables.
 * The only currently supported substitution is `{{TRIAGE_MODEL}}`.
 */
async function readPackagedAsset(assetPath: string, vars?: Record<string, string>): Promise<string> {
  let content = await readFile(assetPath, "utf8");
  if (vars) {
    for (const [key, value] of Object.entries(vars)) {
      content = content.replaceAll(`{{${key}}}`, value);
    }
  }
  return content;
}

/** Describe all plugin assets to install relative to the plugin directory. */
function assetManifest(triageModel: string): Array<{ src: string; dest: string; vars?: Record<string, string> }> {
  const plugin = pluginDir();
  const methodology = METHODOLOGY_FILES.map((file) => ({
    src: path.join(packageRoot(), "methodology", file),
    dest: path.join(".claude", "leanrigor", "methodology", file)
  }));
  return [
    { src: path.join(plugin, "commands", "leanrigor.md"),        dest: path.join(".claude", "commands", "leanrigor.md") },
    { src: path.join(plugin, "commands", "leanrigor-init.md"),   dest: path.join(".claude", "commands", "leanrigor-init.md") },
    { src: path.join(plugin, "commands", "leanrigor-plan.md"),   dest: path.join(".claude", "commands", "leanrigor-plan.md") },
    { src: path.join(plugin, "commands", "leanrigor-status.md"), dest: path.join(".claude", "commands", "leanrigor-status.md") },
    { src: path.join(plugin, "commands", "leanrigor-review.md"), dest: path.join(".claude", "commands", "leanrigor-review.md") },
    { src: path.join(plugin, "commands", "leanrigor-commit.md"), dest: path.join(".claude", "commands", "leanrigor-commit.md") },
    { src: path.join(plugin, "leanrigor", "sequential-workflow.md"), dest: path.join(".claude", "leanrigor", "sequential-workflow.md") },
    {
      src: path.join(plugin, "agents", "leanrigor-triage.md.tpl"),
      dest: path.join(".claude", "agents", "leanrigor-triage.md"),
      vars: { TRIAGE_MODEL: triageModel }
    },
    { src: path.join(plugin, "hooks", "protect-git.sh"),         dest: path.join(".claude", "leanrigor", "protect-git.sh") },
    { src: path.join(plugin, "settings.json"),                   dest: path.join(".claude", "settings.json") },
    ...methodology
  ];
}

export class ClaudeAdapter implements HarnessAdapter {
  name = "claude";

  modelResolver = {
    resolve(tier: ModelTier, config: LeanRigorConfig): string | undefined {
      return resolveModelTier(tier, "claude", config).model;
    }
  };

  async install(root: string, config: LeanRigorConfig, force = false): Promise<InstallReport> {
    const triageModel = resolveModelTier(config.routing.triage, "claude", config).model ?? "haiku";
    const manifest = assetManifest(triageModel);
    const report: InstallReport = { installed: [], alreadyCurrent: [], skipped: [] };

    for (const entry of manifest) {
      const targetPath = path.join(root, entry.dest);
      await mkdir(path.dirname(targetPath), { recursive: true });

      const expected = await readPackagedAsset(entry.src, entry.vars);

      let existing: string | undefined;
      try { existing = await readFile(targetPath, "utf8"); } catch { /* file missing */ }

      if (existing === undefined) {
        // File does not exist — install it
        await writeFile(targetPath, expected, "utf8");
        await ensureExecutableIfHook(entry.dest, targetPath);
        report.installed.push(entry.dest);
      } else if (sha256(existing) === sha256(expected)) {
        // File exists and is identical to the packaged version
        await ensureExecutableIfHook(entry.dest, targetPath);
        report.alreadyCurrent.push(entry.dest);
      } else if (isLeanRigorOwned(existing) && force) {
        // File is owned and user requested force-replace
        await writeFile(targetPath, expected, "utf8");
        await ensureExecutableIfHook(entry.dest, targetPath);
        report.installed.push(entry.dest);
      } else {
        // User file or user-modified owned file — do not overwrite
        report.skipped.push(entry.dest);
      }
    }

    return report;
  }

  async uninstall(root: string): Promise<UninstallReport> {
    const config = await loadConfigForUninstall(root);
    const triageModel = resolveModelTier(config.routing.triage, "claude", config).model ?? "haiku";
    const manifest = assetManifest(triageModel);
    const report: UninstallReport = { removed: [], skipped: [] };

    for (const entry of manifest) {
      const targetPath = path.join(root, entry.dest);
      let existing: string | undefined;
      try { existing = await readFile(targetPath, "utf8"); } catch { /* file missing — nothing to remove */ }

      if (existing === undefined) continue;

      if (!isLeanRigorOwned(existing)) {
        report.skipped.push(entry.dest);
        continue;
      }

      // Hash comparison detects user modifications. Note: for template-based assets
      // (e.g. leanrigor-triage.md) the expected content depends on the current config.
      // If the triage model was changed after installation, the hashes will differ even
      // without user edits. In that case the file is skipped (preserved), which is the
      // safe default. To remove all LeanRigor-owned files, delete them manually or run
      // `leanrigor uninstall --adapter claude` after resetting the config to the original
      // model tier.
      const expected = await readPackagedAsset(entry.src, entry.vars).catch(() => undefined);
      if (expected !== undefined && sha256(existing) !== sha256(expected)) {
        // User has modified this owned file (or config changed) — preserve it
        report.skipped.push(entry.dest);
        continue;
      }

      await unlink(targetPath);
      report.removed.push(entry.dest);

      // Remove the parent directory and ancestor directories up to .claude/ if now empty
      const claudeDir = path.join(root, ".claude");
      let dir = path.dirname(targetPath);
      while (dir.length > claudeDir.length && dir.startsWith(claudeDir)) {
        const removed = await removeIfEmpty(dir);
        if (!removed) break; // Directory still has contents — stop climbing
        dir = path.dirname(dir);
      }
      await removeIfEmpty(claudeDir);
    }

    return report;
  }

  async doctor(root: string, config: LeanRigorConfig): Promise<string[]> {
    const output: string[] = [];
    const packageVersion = await readPackageVersion();
    output.push(`LeanRigor CLI: ${packageVersion}`);
    output.push(`Platform: Claude Code`);
    output.push(`Claude assets available: ${ASSET_VERSION}`);
    output.push(`Runtime source: ${runtimeSource()}`);

    // Configuration files found
    output.push("");
    output.push("Configuration files:");
    const userConfig = await loadUserConfig();
    output.push(`  User config (~/.config/leanrigor/config.json): ${userConfig ? "found" : "not found"}`);
    const repoPolicy = await loadRepoPolicy(root);
    output.push(`  Repository policy (leanrigor.config.json): ${repoPolicy ? "found" : "not found"}`);
    const localExists = await configFileExists(ConfigScope.Local, root);
    output.push(`  Local config (.leanrigor/config.json): ${localExists ? "found" : "not found (using defaults)"}`);

    // .leanrigor/.gitignore status
    output.push("");
    const gitignoreStatus = await ensureGitignore(path.join(root, ".leanrigor"));
    output.push(gitignoreStatus.message);

    // Check for tracked .leanrigor files
    const trackedFiles = await checkTrackedLeanrigorFiles(root);
    if (trackedFiles.length > 0) {
      output.push(`⚠ WARNING: ${trackedFiles.length} file(s) in .leanrigor/ may be tracked by Git:`);
      for (const file of trackedFiles) {
        output.push(`  .leanrigor/${file}`);
      }
      output.push("  These files contain private runtime state and should not be committed.");
    }

    // Check Claude CLI availability — check PATH first, then common fallback location
    const claudeInPath = await which("claude");
    if (claudeInPath) {
      output.push(`Claude CLI: found (${claudeInPath})`);
    } else {
      try {
        await access("/usr/local/bin/claude");
        output.push("Claude CLI: found at /usr/local/bin/claude");
      } catch {
        output.push("Claude CLI: not found on PATH");
      }
    }

    // Check model tier resolution with provenance
    output.push("");
    output.push("Model tier resolution:");
    for (const tier of ["small", "medium", "large"] as const) {
      try {
        const resolved = resolveModelTier(tier, "claude", config);
        const detail = resolved.model && isClaudeAlias(resolved.model) ? "Claude alias" : "custom identifier";
        const sourceLabel = modelSourceLabel(resolved.source);
        output.push(`  ${tier}: ${resolved.model ?? "inherit"} (source: ${sourceLabel}${resolved.model ? `, ${detail}` : ""})`);
      } catch (error) { output.push(`  ${tier}: ERROR — ${(error as Error).message}`); }
    }

    // Check installed assets
    const triageModel = resolveModelTier(config.routing.triage, "claude", config).model ?? "haiku";
    const manifest = assetManifest(triageModel);
    let installedCount = 0;
    const missingAssets: string[] = [];
    const currentAssets: string[] = [];
    const conflictAssets: string[] = [];
    const modifiedOwnedAssets: string[] = [];
    let protectGitState = "protect-git.sh: missing";

    for (const entry of manifest) {
      const targetPath = path.join(root, entry.dest);
      let existing: string | undefined;
      try { existing = await readFile(targetPath, "utf8"); } catch { /* missing */ }

      if (existing === undefined) {
        missingAssets.push(entry.dest);
        if (isProtectGit(entry.dest)) protectGitState = "protect-git.sh: missing";
        continue;
      }

      installedCount += 1;
      const expected = await readPackagedAsset(entry.src, entry.vars).catch(() => undefined);
      if (!isLeanRigorOwned(existing)) {
        conflictAssets.push(entry.dest);
        if (isProtectGit(entry.dest)) protectGitState = "protect-git.sh: modified";
      } else if (expected !== undefined && sha256(existing) === sha256(expected)) {
        currentAssets.push(entry.dest);
        if (isProtectGit(entry.dest)) {
          protectGitState = await isExecutable(targetPath)
            ? "protect-git.sh: current and executable"
            : "protect-git.sh: installed but not executable";
        }
      } else {
        modifiedOwnedAssets.push(entry.dest);
        if (isProtectGit(entry.dest)) protectGitState = "protect-git.sh: modified";
      }
    }

    const totalAvailable = manifest.length;
    output.push("");
    output.push(`Claude assets installed: ${installedCount}/${totalAvailable}`);
    if (missingAssets.length === 0 && conflictAssets.length === 0 && modifiedOwnedAssets.length === 0) {
      output.push("Status: current");
    } else {
      output.push("Status: incomplete or needs attention");
    }

    if (currentAssets.length > 0) {
      output.push("");
      output.push("Current:");
      for (const f of currentAssets) output.push(`  ${f}`);
    }
    output.push("");
    output.push(protectGitState);
    if (missingAssets.length > 0) {
      output.push("");
      output.push("Missing (run `leanrigor init --adapter claude` to install):");
      for (const f of missingAssets) output.push(`  ${f}`);
    }
    if (modifiedOwnedAssets.length > 0) {
      output.push("");
      output.push("Modified (LeanRigor-owned files with local changes):");
      for (const f of modifiedOwnedAssets) output.push(`  ${f}`);
      output.push("  Use `leanrigor init --adapter claude --force-owned-files` to restore.");
    }
    if (conflictAssets.length > 0) {
      output.push("");
      output.push("Conflict (non-LeanRigor files in expected locations):");
      for (const f of conflictAssets) output.push(`  ${f}`);
    }

    // Workflow settings
    output.push("");
    output.push(`Automatic triage: ${config.workflow.automaticTriage ? "enabled" : "disabled"}`);

    // Config management hints
    output.push("");
    output.push("Configuration management:");
    output.push("  Show effective config: leanrigor config show");
    output.push("  Show config detail:   leanrigor config show --json");
    output.push("  Change user setting:   leanrigor config set <path> <value> --scope user");
    output.push("  Change repo policy:    leanrigor config set <path> <value> --scope repo");
    output.push("  Change local setting:  leanrigor config set <path> <value> --scope local");

    return output;
  }
}

function isProtectGit(dest: string): boolean {
  return dest === PROTECT_GIT_DEST;
}

async function ensureExecutableIfHook(dest: string, targetPath: string): Promise<void> {
  if (isProtectGit(dest)) await chmod(targetPath, 0o755);
}

async function isExecutable(targetPath: string): Promise<boolean> {
  if (process.platform === "win32") return true;
  try {
    const mode = (await stat(targetPath)).mode;
    return (mode & 0o111) !== 0;
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function removeIfEmpty(dir: string): Promise<boolean> {
  try {
    const entries = await readdir(dir);
    if (entries.length === 0) {
      await rmdir(dir).catch(() => { /* ignore: may not be removable (race condition or permissions) */ });
      return true;
    }
    return false;
  } catch { /* ignore: directory may not exist */ }
  return false;
}

async function which(command: string): Promise<string | undefined> {
  const { spawn } = await import("node:child_process");
  return new Promise((resolve) => {
    const child = spawn("which", [command], { stdio: ["ignore", "pipe", "ignore"] });
    let out = "";
    child.stdout?.on("data", (chunk: Buffer) => { out += chunk.toString(); });
    child.on("close", (code: number | null) => {
      resolve(code === 0 ? out.trim() : undefined);
    });
    child.on("error", () => resolve(undefined));
  });
}

async function readPackageVersion(): Promise<string> {
  try {
    // Walk up from plugin dir to find package.json
    const packageJsonPath = fileURLToPath(new URL("../../../package.json", import.meta.url));
    const pkg = JSON.parse(await readFile(packageJsonPath, "utf8")) as { version?: string };
    return pkg.version ?? "unknown";
  } catch {
    return "unknown";
  }
}

function runtimeSource(): string {
  if (process.env.LEANRIGOR_RUNTIME_SOURCE === "claude-marketplace-plugin" || process.env.LEANRIGOR_CLAUDE_PLUGIN_ROOT || process.env.CLAUDE_PLUGIN_ROOT) {
    return "marketplace plugin runtime";
  }
  if (process.argv[1]?.includes(`${path.sep}node_modules${path.sep}`)) return "npm package CLI";
  return "local development or global CLI";
}

/** Load config for uninstall without crashing if config is missing. */
async function loadConfigForUninstall(root: string): Promise<LeanRigorConfig> {
  try {
    const { loadConfig } = await import("../../config/load.js");
    return loadConfig(root);
  } catch {
    const { defaultConfig } = await import("../../config/defaults.js");
    return defaultConfig();
  }
}

/** Human-readable label for model resolution sources. */
function modelSourceLabel(source: string): string {
  switch (source) {
    case "adapter-env": return "ANTHROPIC_DEFAULT_* environment variable";
    case "platform-env": return "LEANRIGOR_CLAUDE_MODEL_* environment variable";
    case "generic-env": return "LEANRIGOR_MODEL_* environment variable";
    case "config": return "LeanRigor configuration file";
    case "adapter-default": return "Claude alias default (haiku/sonnet/opus)";
    case "inherit": return "inherited (no model specified)";
    default: return source;
  }
}
