import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { access, mkdir, readFile, readdir, rmdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import type { HarnessAdapter, InstallReport, UninstallReport } from "../types.js";
import type { LeanRigorConfig, ModelTier } from "../../config/schema.js";
import { isClaudeAlias, resolveModelTier } from "../../config/models.js";

/** Version stamp embedded in every generated asset. Increment when assets change in a breaking way. */
export const ASSET_VERSION = 1;

/** String embedded in every LeanRigor-generated file for ownership detection. */
const OWNERSHIP_TOKEN = "generated_by: leanrigor";

/** Directory containing the Claude plugin source assets, resolved at runtime. */
function pluginDir(): string {
  return fileURLToPath(new URL("./plugin/", import.meta.url));
}

/** Deterministic SHA-256 of a string. */
function sha256(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex");
}

/** Return true when the file content was generated by LeanRigor. */
function isLeanRigorOwned(content: string): boolean {
  return content.includes(OWNERSHIP_TOKEN);
}

/**
 * Read a packaged asset and optionally substitute template variables.
 * The only currently supported substitution is `{{TRIAGE_MODEL}}`.
 */
async function readPackagedAsset(assetPath: string, vars?: Record<string, string>): Promise<string> {
  let content = await readFile(assetPath, "utf8");
  if (vars) {
    for (const [key, value] of Object.entries(vars)) {
      content = content.replaceAll(`{{${key}}}`, value);
    }
  }
  return content;
}

/** Describe all plugin assets to install relative to the plugin directory. */
function assetManifest(triageModel: string): Array<{ src: string; dest: string; vars?: Record<string, string> }> {
  const plugin = pluginDir();
  return [
    { src: path.join(plugin, "commands", "leanrigor.md"),        dest: path.join(".claude", "commands", "leanrigor.md") },
    { src: path.join(plugin, "commands", "leanrigor-plan.md"),   dest: path.join(".claude", "commands", "leanrigor-plan.md") },
    { src: path.join(plugin, "commands", "leanrigor-status.md"), dest: path.join(".claude", "commands", "leanrigor-status.md") },
    { src: path.join(plugin, "commands", "leanrigor-review.md"), dest: path.join(".claude", "commands", "leanrigor-review.md") },
    { src: path.join(plugin, "commands", "leanrigor-commit.md"), dest: path.join(".claude", "commands", "leanrigor-commit.md") },
    {
      src: path.join(plugin, "agents", "leanrigor-triage.md.tpl"),
      dest: path.join(".claude", "agents", "leanrigor-triage.md"),
      vars: { TRIAGE_MODEL: triageModel }
    },
    { src: path.join(plugin, "hooks", "protect-git.sh"),         dest: path.join(".claude", "leanrigor", "protect-git.sh") },
    { src: path.join(plugin, "settings.json"),                   dest: path.join(".claude", "settings.json") },
  ];
}

export class ClaudeAdapter implements HarnessAdapter {
  name = "claude";

  modelResolver = {
    resolve(tier: ModelTier, config: LeanRigorConfig): string | undefined {
      return resolveModelTier(tier, "claude", config).model;
    }
  };

  async install(root: string, config: LeanRigorConfig, force = false): Promise<InstallReport> {
    const triageModel = resolveModelTier(config.routing.triage, "claude", config).model ?? "haiku";
    const manifest = assetManifest(triageModel);
    const report: InstallReport = { installed: [], alreadyCurrent: [], skipped: [] };

    for (const entry of manifest) {
      const targetPath = path.join(root, entry.dest);
      await mkdir(path.dirname(targetPath), { recursive: true });

      const expected = await readPackagedAsset(entry.src, entry.vars);

      let existing: string | undefined;
      try { existing = await readFile(targetPath, "utf8"); } catch { /* file missing */ }

      if (existing === undefined) {
        // File does not exist — install it
        await writeFile(targetPath, expected, "utf8");
        report.installed.push(entry.dest);
      } else if (sha256(existing) === sha256(expected)) {
        // File exists and is identical to the packaged version
        report.alreadyCurrent.push(entry.dest);
      } else if (isLeanRigorOwned(existing) && force) {
        // File is owned and user requested force-replace
        await writeFile(targetPath, expected, "utf8");
        report.installed.push(entry.dest);
      } else {
        // User file or user-modified owned file — do not overwrite
        report.skipped.push(entry.dest);
      }
    }

    return report;
  }

  async uninstall(root: string): Promise<UninstallReport> {
    const config = await loadConfigForUninstall(root);
    const triageModel = resolveModelTier(config.routing.triage, "claude", config).model ?? "haiku";
    const manifest = assetManifest(triageModel);
    const report: UninstallReport = { removed: [], skipped: [] };

    for (const entry of manifest) {
      const targetPath = path.join(root, entry.dest);
      let existing: string | undefined;
      try { existing = await readFile(targetPath, "utf8"); } catch { /* file missing — nothing to remove */ }

      if (existing === undefined) continue;

      if (!isLeanRigorOwned(existing)) {
        report.skipped.push(entry.dest);
        continue;
      }

      const expected = await readPackagedAsset(entry.src, entry.vars).catch(() => undefined);
      if (expected !== undefined && sha256(existing) !== sha256(expected)) {
        // User has modified this owned file — preserve it
        report.skipped.push(entry.dest);
        continue;
      }

      await unlink(targetPath);
      report.removed.push(entry.dest);

      // Remove the parent directory if it is now empty and is a LeanRigor-created directory
      await removeIfEmpty(path.dirname(targetPath));
    }

    return report;
  }

  async doctor(root: string, config: LeanRigorConfig): Promise<string[]> {
    const output: string[] = [];
    const packageVersion = await readPackageVersion();
    output.push(`LeanRigor CLI: ${packageVersion}`);
    output.push(`Platform: Claude Code`);
    output.push(`Claude assets available: ${ASSET_VERSION}`);

    // Check Claude CLI availability — check PATH first, then common fallback location
    const claudeInPath = await which("claude");
    if (claudeInPath) {
      output.push(`Claude CLI: found (${claudeInPath})`);
    } else {
      try {
        await access("/usr/local/bin/claude");
        output.push("Claude CLI: found at /usr/local/bin/claude");
      } catch {
        output.push("Claude CLI: not found on PATH");
      }
    }

    // Check model tier resolution
    output.push("");
    output.push("Model tier resolution:");
    for (const tier of ["small", "medium", "large"] as const) {
      try {
        const resolved = resolveModelTier(tier, "claude", config);
        const detail = resolved.model && isClaudeAlias(resolved.model) ? "Claude alias" : "custom identifier";
        output.push(`  ${tier}: ${resolved.model ?? "inherit"} (source: ${resolved.source}${resolved.model ? `, ${detail}` : ""})`);
      } catch (error) { output.push(`  ${tier}: ERROR — ${(error as Error).message}`); }
    }

    // Check installed assets
    const triageModel = resolveModelTier(config.routing.triage, "claude", config).model ?? "haiku";
    const manifest = assetManifest(triageModel);
    let installedCount = 0;
    const missingAssets: string[] = [];
    const currentAssets: string[] = [];
    const conflictAssets: string[] = [];
    const modifiedOwnedAssets: string[] = [];

    for (const entry of manifest) {
      const targetPath = path.join(root, entry.dest);
      let existing: string | undefined;
      try { existing = await readFile(targetPath, "utf8"); } catch { /* missing */ }

      if (existing === undefined) {
        missingAssets.push(entry.dest);
        continue;
      }

      installedCount += 1;
      const expected = await readPackagedAsset(entry.src, entry.vars).catch(() => undefined);
      if (!isLeanRigorOwned(existing)) {
        conflictAssets.push(entry.dest);
      } else if (expected !== undefined && sha256(existing) === sha256(expected)) {
        currentAssets.push(entry.dest);
      } else {
        modifiedOwnedAssets.push(entry.dest);
      }
    }

    const totalAvailable = manifest.length;
    output.push("");
    output.push(`Claude assets installed: ${installedCount}/${totalAvailable}`);
    if (missingAssets.length === 0 && conflictAssets.length === 0 && modifiedOwnedAssets.length === 0) {
      output.push("Status: current");
    } else {
      output.push("Status: incomplete or needs attention");
    }

    if (currentAssets.length > 0) {
      output.push("");
      output.push("Current:");
      for (const f of currentAssets) output.push(`  ${f}`);
    }
    if (missingAssets.length > 0) {
      output.push("");
      output.push("Missing (run `leanrigor init --adapter claude` to install):");
      for (const f of missingAssets) output.push(`  ${f}`);
    }
    if (modifiedOwnedAssets.length > 0) {
      output.push("");
      output.push("Modified (LeanRigor-owned files with local changes):");
      for (const f of modifiedOwnedAssets) output.push(`  ${f}`);
      output.push("  Use `leanrigor init --adapter claude --force-owned-files` to restore.");
    }
    if (conflictAssets.length > 0) {
      output.push("");
      output.push("Conflict (non-LeanRigor files in expected locations):");
      for (const f of conflictAssets) output.push(`  ${f}`);
    }

    // Workflow settings
    output.push("");
    output.push(`Automatic triage: ${config.workflow.automaticTriage ? "enabled" : "disabled"}`);

    return output;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function removeIfEmpty(dir: string): Promise<void> {
  try {
    const entries = await readdir(dir);
    if (entries.length === 0) {
      await rmdir(dir).catch(() => { /* ignore: may not be removable (race condition or permissions) */ });
    }
  } catch { /* ignore: directory may not exist */ }
}

async function which(command: string): Promise<string | undefined> {
  const { spawn } = await import("node:child_process");
  return new Promise((resolve) => {
    const child = spawn("which", [command], { stdio: ["ignore", "pipe", "ignore"] });
    let out = "";
    child.stdout?.on("data", (chunk: Buffer) => { out += chunk.toString(); });
    child.on("close", (code: number | null) => {
      resolve(code === 0 ? out.trim() : undefined);
    });
    child.on("error", () => resolve(undefined));
  });
}

async function readPackageVersion(): Promise<string> {
  try {
    // Walk up from plugin dir to find package.json
    const packageJsonPath = fileURLToPath(new URL("../../../package.json", import.meta.url));
    const pkg = JSON.parse(await readFile(packageJsonPath, "utf8")) as { version?: string };
    return pkg.version ?? "unknown";
  } catch {
    return "unknown";
  }
}

/** Load config for uninstall without crashing if config is missing. */
async function loadConfigForUninstall(root: string): Promise<LeanRigorConfig> {
  try {
    const { loadConfig } = await import("../../config/load.js");
    return loadConfig(root);
  } catch {
    const { defaultConfig } = await import("../../config/defaults.js");
    return defaultConfig();
  }
}

